Добавляет стили для высококнагруженных форм
Flexberry/ember-flexberry-themes pull request #102
Opened 2022-08-15 09:56 UTC by mari4orl

2022-09-06 13:15 UTC, pepelyaeva requested changes

2022-09-06 13:15 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  background-color: @highloadedMenuNextBtnColor;
Кнопка должна быть не розовой а цвета @primaryColor

2022-09-06 13:15 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +.button-container {
button-container слишком общий селектор, для стилей конкретного компонента лучше использовать еще название компонента.

2022-09-06 13:15 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  display: flex;
Почему кнопки не вынести column просто?

2022-09-06 13:15 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  padding: 0.7em;
Почему 16? в макете вроде 14рх шрифт, и кнопки во всем приложении должны быть единообразными, надо отступ оставить дефолтным

2022-09-06 13:15 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  color: @secondaryColor;
Нужно задать через переменные семантика цвет @secondaryColor для .empty кнопки

2022-09-06 13:15 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-highloadedmenu.variables
> +@highloadedMenuGreen: #71BC90;
Все цвета должны браться из global темы

2022-09-07 10:05 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  background-color: @highloadedMenuNextBtnColor;
Исправлено

2022-09-07 10:06 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +.button-container {
Исправлено (убрала вообще контейнер потому что не нужен)

2022-09-07 10:06 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  display: flex;
исправлено

2022-09-07 10:07 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  padding: 0.7em;
исправлено

2022-09-07 10:08 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  color: @secondaryColor;
исправлено

2022-09-07 10:08 UTC, mari4orl commented on src/themes/ghost/components/flexberry-highloadedmenu.variables
> +@highloadedMenuGreen: #71BC90;
исправлено

2022-09-07 11:21 UTC, pepelyaeva requested changes

2022-09-07 11:21 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  font-size: @highloadedMenuHeaderFontSize;
18px в макете, а тут 16. и тут отступ надо добавить

2022-09-07 11:21 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  h3.ui.header {
h3.ui.header.title, а то для цифры это тоже работает и там много переопределений

2022-09-07 11:21 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +    color: @blueZodiak;
@textColor

2022-09-07 11:21 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +    font-size: @highloadedMenuIconFontSize;
Луше только для звездочки это задать, на форме могут быть другие small.icon

2022-09-07 11:21 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  color: @secondaryColor;
Сорян, не в семантике, в нашей теме, [тут](https://github.com/Flexberry/ember-flexberry-themes/blob/develop/src/themes/ghost/components/flexberry-button.variables#L37) , задать @secondaryColor . basic.secondary это будет кнопка цвета @secondaryColor с бордером, нужна empty

2022-09-08 06:26 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +    font-size: @highloadedMenuIconFontSize;
Исправлено

2022-09-08 06:26 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +    color: @blueZodiak;
Исправлено

2022-09-08 06:26 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  h3.ui.header {
Исправлено

2022-09-08 06:27 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  font-size: @highloadedMenuHeaderFontSize;
Исправлено

2022-09-08 06:27 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  color: @secondaryColor;
Исправлено

2022-09-16 12:55 UTC, pepelyaeva approved these changes

2022-09-16 12:55 UTC, merged