Замена иконок
Flexberry/ember-flexberry-themes pull request #109
Opened 2023-02-01 08:55 UTC by mari4orl

2023-02-07 11:06 UTC, pepelyaeva requested changes

2023-02-07 11:06 UTC, pepelyaeva commented on src/themes/ghost/globals/site.variables
> +@glyphWidth: 1.7em;
Теперь везде размер иконки увеличился, где @glyphWidth использовался в качестве размера шрифта. Em - это относительно размера шрифта элемента, везде разная величина будет.

Везде должен быть единый размер иконки. Давай заведем отдельную переменную в site.variables
```
// Icons size
@iconSize         : 1.5rem;
```
и ее везде поиспользуем, чтобы у всех иконок был один размер. 1.5rem как раз будет 24px, сейчас размер шрифта в дате, например, 23.8px.

2023-02-07 11:06 UTC, pepelyaeva commented on src/themes/blue-sky/globals/site.variables
> +@glyphWidth: 1.7em;
Для blue-sky зачем доработки? там этот шрифт не используется

2023-02-07 11:06 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-lookup.overrides
> +    font-size: 1.2em;
Везде должен быть единый размер иконки

2023-02-07 11:06 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-objectlistview.overrides
> +        font-size: 1.4rem;
Это зачем?

2023-02-08 11:10 UTC, mari4orl commented on src/themes/ghost/components/flexberry-objectlistview.overrides
> +        font-size: 1.4rem;
Исправлено

2023-02-08 11:11 UTC, mari4orl commented on src/themes/ghost/components/flexberry-lookup.overrides
> +    font-size: 1.2em;
Исправлено

2023-02-08 11:12 UTC, mari4orl commented on src/themes/blue-sky/globals/site.variables
> +@glyphWidth: 1.7em;
Исправлено

2023-02-08 11:12 UTC, mari4orl commented on src/themes/ghost/globals/site.variables
> +@glyphWidth: 1.7em;
Исправлено

2023-02-08 12:33 UTC, pepelyaeva requested changes

2023-02-08 12:33 UTC, pepelyaeva commented on src/definitions/pages/main.less
> +    font-size: @iconSize;
Нужно вернуть и в main.variables указать @userIconSize: @iconSize

2023-02-08 12:33 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-file.overrides
> +      font-size: @iconSize;
Давай этот компонент отдельно заменять? сейчас у него еще старые иконки  и выглядят теперь очень большими

2023-02-08 12:33 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-lookup.overrides
> +  font-size: @iconSize;
@lookupIconFontSize: @iconSize; в  .variables  здесь и ниже. Еще выравнивание куда-то поехало 
![image](https://user-images.githubusercontent.com/15091209/217523622-eab0530e-7798-4747-8318-92024b9afadd.png)

2023-02-08 12:33 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-lookup.overrides
> +    font-size: @iconSize;
Зачем это еще раз указывать? у кнопки же уже установлен размер шрифта

2023-02-08 12:33 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-simpledatetime.overrides
> +  font-size: @iconSize;
@inputIconFontSize: @iconSize

2023-02-08 12:33 UTC, pepelyaeva commented on src/themes/ghost/pages/edit-form.overrides
> +    font-size: @iconSize;
ты же уже присвоила @iconFontSize   : @iconSize;

2023-02-08 12:44 UTC, pepelyaeva commented on src/themes/ghost/pages/edit-form.variables
> +@iconFontSize   : @iconSize;
Давай пока 1rem оставим? какие-то они огромные стали)

2023-02-09 08:39 UTC, mari4orl commented on src/themes/ghost/components/flexberry-simpledatetime.overrides
> +  font-size: @iconSize;
Исправлено

2023-02-09 08:40 UTC, mari4orl commented on src/themes/ghost/components/flexberry-lookup.overrides
> +    font-size: @iconSize;
Исправлено

2023-02-09 08:40 UTC, mari4orl commented on src/themes/ghost/components/flexberry-file.overrides
> +      font-size: @iconSize;
Исправлено

2023-02-09 08:40 UTC, mari4orl commented on src/definitions/pages/main.less
> +    font-size: @iconSize;
Исправлено

2023-02-09 08:45 UTC, mari4orl commented on src/themes/ghost/pages/edit-form.overrides
> +    font-size: @iconSize;
Исправлено

2023-02-09 08:47 UTC, mari4orl commented on src/themes/ghost/pages/edit-form.variables
> +@iconFontSize   : @iconSize;
Исправлено

2023-02-09 09:14 UTC, mari4orl commented on src/themes/ghost/components/flexberry-lookup.overrides
> +  font-size: @iconSize;
Исправлено

2023-02-09 10:33 UTC, pepelyaeva approved these changes

2023-02-09 10:35 UTC, merged