Заменить оставшиеся иконки компонентов на новые
Flexberry/ember-flexberry-themes pull request #110
Opened 2023-02-16 10:11 UTC by mari4orl

2023-02-27 11:29 UTC, pepelyaeva requested changes

2023-02-27 11:29 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-dropdown.overrides
> +  right: 13px;
1. Почему 13? Сверху/снизу 8, справа 6 по макету.
2. Эти значения задаются через переменные 
![image](https://user-images.githubusercontent.com/15091209/221545456-e312d2c7-4a0c-4622-8796-f748be5e7eed.png)

2023-02-27 11:29 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
> +  margin-bottom: 4px;
```suggestion
  margin: 0 2px 0 -2px;
  height: auto;
  width: auto;
```

2023-02-27 11:29 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
>  }
Вот это надо убрать и [тут](https://github.com/Flexberry/ember-flexberry-themes/blob/develop/src/themes/ghost/components/flexberry-button.overrides#L60) прописать :not(.primary):not(.empty)

2023-02-27 14:53 UTC, mari4orl commented on src/themes/ghost/components/flexberry-dropdown.overrides
> +  right: 13px;
Исправлено

2023-02-27 14:53 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
> +  margin-bottom: 4px;
Исправлено

2023-02-27 14:53 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
>  }
Исправлено

2023-02-27 15:37 UTC, pepelyaeva commented on src/definitions/components/flexberry-highloadedmenu.less
>  }
Это можно убрать тоже, в flexberry-button.overrides прописали же :not(.empty)

2023-02-28 06:21 UTC, mari4orl commented on src/definitions/components/flexberry-highloadedmenu.less
>  }
Исправлено

2023-02-28 07:15 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-button.overrides
> +.ui.button:not(.disabled) i.icon:not(.primary):not(.empty) {
```suggestion
.ui.button:not(.disabled):not(.primary):not(.empty) i.icon {
```
Это чтобы не перекрашивать самостоятельно иконки если кнопка primary или empty

2023-02-28 10:56 UTC, mari4orl commented on src/themes/ghost/components/flexberry-button.overrides
> +.ui.button:not(.disabled) i.icon:not(.primary):not(.empty) {
Исправлено

2023-02-28 11:00 UTC, merged