Add new icon basket
Flexberry/ember-flexberry-themes pull request #144
Opened 2023-09-11 09:20 UTC by ronzhak

2023-09-25 13:29 UTC, pepelyaeva commented on src/themes/ghost/assets/fonts/guideline-icons/selection.json
> +{"IcoMoonType":"selection","icons":[{"icon":{"paths":["M256 816.764c0 43.58 38.4 79.236 85.333 79.236h341.333c46.933 0 85.333-35.657 85.333-79.236v-432.764c0-23.564-19.102-42.667-42.667-42.667s-42.66
Там версия шрифта 2.6 была. Тут почему-то 1.0
![image](https://github.com/Flexberry/ember-flexberry-themes/assets/15091209/9881a36d-a4d1-4824-8e18-9385078c6f28)

2023-09-25 13:31 UTC, pepelyaeva requested changes
А где css`ка?

2023-09-25 13:31 UTC, pepelyaeva commented on src/themes/ghost/assets/fonts/guideline-icons/selection.json
> +{"IcoMoonType":"selection","icons":[{"icon":{"paths":["M256 816.764c0 43.58 38.4 79.236 85.333 79.236h341.333c46.933 0 85.333-35.657 85.333-79.236v-432.764c0-23.564-19.102-42.667-42.667-42.667s-42.66
Там версия шрифта 2.6 была. Тут почему-то 1.0
![image](https://github.com/Flexberry/ember-flexberry-themes/assets/15091209/9881a36d-a4d1-4824-8e18-9385078c6f28)

2023-09-25 13:31 UTC, pepelyaeva commented on src/themes/ghost/pages/edit-form.variables
> +@iconPadding      : 0.25em;
Это надо откатить

2023-09-27 05:58 UTC, ronzhak commented
> А где css`ка?

Код картинки тот же остался.

2023-09-28 10:20 UTC, pepelyaeva approved these changes

2023-09-28 10:20 UTC, merged