Sidepage на весь экран в мобильной версии
Flexberry/ember-flexberry-themes pull request #55
Opened 2020-04-07 04:27 UTC by rkapkannikov

Sidepage на весь экран в мобильной версии.

2020-04-07 14:26 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +.mobile .ui.small.modal.flexberry-sidepage  {
До окон лукапа не доходит данный селектор, они не .small

2020-04-07 14:29 UTC, pepelyaeva requested changes

2020-04-07 14:29 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +.mobile .ui.small.modal.flexberry-sidepage  {
До окон лукапа не доходит данный селектор, они не .small

2020-04-08 05:05 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-modal.overrides
> +.mobile .ui.small.modal.flexberry-sidepage  {
Убрал .small

2020-04-10 07:47 UTC, pepelyaeva approved these changes

2020-04-10 07:48 UTC, merged