Изменён размер логотипа
Flexberry/ember-flexberry-themes pull request #56
Opened 2020-04-07 07:29 UTC by rkapkannikov

Изменён размер логотипа.

2020-04-10 11:20 UTC, pepelyaeva requested changes

2020-04-10 11:20 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +  width: @logoMobile;
Ширина иконки не должна уменьшаться с изменением размера окна. Минимальный размер окна 360рх. Расстояние от логотипа до заголовка 16рх, от логотипа до иконки бургера - 24рх.

2020-04-13 12:10 UTC, rkapkannikov commented on src/themes/gos/pages/main.overrides
> +  width: @logoMobile;
Исправлено

2020-04-15 10:22 UTC, pepelyaeva requested changes

2020-04-15 10:22 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +=======
Делай мердж аккуратнее, пожалуйста.

2020-04-15 10:22 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +>>>>>>> .merge_file_a26988
Делай мердж аккуратнее, пожалуйста.

2020-04-23 09:46 UTC, pepelyaeva commented
Размер внешнего блока логотипа все еще 72px, поэтому от самой картинки до заголовка все еще большое расстояние на разрешении > 500. Также иконка пользователя должна быть прижата к левому краю.
![image](https://user-images.githubusercontent.com/15091209/80084510-66750d80-8570-11ea-95dd-3e3e66d36cf1.png)

2020-04-23 09:46 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +  a.item.logo {
Нужно убрать тег из селектора там, где он не нужен. Ниже также.

2020-04-23 09:47 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +    padding: 0px;
В переменную.

2020-04-23 09:48 UTC, pepelyaeva commented on src/themes/gos/pages/main.overrides
> +    width: auto;
Это на что-то влияет? Там вроде итак ширина не задается.

2020-04-24 11:48 UTC, pepelyaeva requested changes
Размер внешнего блока логотипа все еще 72px, поэтому от самой картинки до заголовка все еще большое расстояние на разрешении > 500. Также иконка пользователя должна быть прижата к правому краю.
![image](https://user-images.githubusercontent.com/15091209/80084510-66750d80-8570-11ea-95dd-3e3e66d36cf1.png)

2020-04-24 11:55 UTC, rkapkannikov commented on src/themes/gos/pages/main.overrides
> +  a.item.logo {
Убрал

2020-04-24 11:55 UTC, rkapkannikov commented on src/themes/gos/pages/main.overrides
> +    padding: 0px;
Вынес в переменную

2020-04-24 11:55 UTC, rkapkannikov commented on src/themes/gos/pages/main.overrides
> +    width: auto;
Убрал

2020-04-24 11:56 UTC, pepelyaeva requested changes

2020-04-24 11:56 UTC, pepelyaeva commented on src/themes/gos/pages/login-form.overrides
> +}
Зачем в эту ветку сливать ветку для логин-формы?

2020-04-25 08:32 UTC, closed without merging