Стили для формы обратной связи
Flexberry/ember-flexberry-themes pull request #58
Opened 2020-04-09 07:35 UTC by rkapkannikov

Были добавлены стили для формы обратной связи.

2020-04-10 07:14 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +    color: @lightGrayishBlue;
@secondaryColor

2020-04-10 07:14 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +    font-size: @modalContactsFontSiza;
Опечатка

2020-04-10 10:32 UTC, pepelyaeva requested changes
Нужно убрать скругление у всего окна и уменьшить расстояние между заголовком и контактами

2020-04-13 12:46 UTC, rkapkannikov commented
Убрал скругления окна и отступ от заголовка

2020-04-15 10:22 UTC, pepelyaeva requested changes

2020-04-15 10:22 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +.ui.modal.flexberry-modal.modal-support.tiny {
Делай мердж аккуратнее, пожалуйста.

2020-04-23 09:11 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +  }
Почему бы это не объединить? Одинаковые же стили.

2020-04-23 09:17 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +    padding-top: 0px !important;
Вместо этого нужно задать переменную семантика [@mobileDescriptionPadding](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/modal.less#L260).

2020-04-23 09:18 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +  border-radius: 0px;
Лучше перенести наверх под объявление селектора.

2020-04-23 09:22 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-modal.overrides
> +    padding-top: 0px !important;
Нужно в переменную вынести, чтобы можно было потом переопределить.

2020-04-27 05:11 UTC, closed without merging