Feature 198918 - Added mobile styles for row controls
Flexberry/ember-flexberry-themes pull request #59
Opened 2020-04-13 09:15 UTC by dslekomtsev

2020-04-15 10:41 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-objectlistview.overrides
> +          content: @deleteHelperButtonInRowIcon;
Получится это как-то объединить с объявлением стилей для десктопных кнопок?

2020-04-15 10:53 UTC, pepelyaeva requested changes
Focus на кнопке надо убрать, сейчас синим выделяется. Думаю, можно сделать на фокус затемнение иконки.
Расстояние между иконками нужно поменьше сделать

2020-04-20 06:23 UTC, dslekomtsev commented on src/themes/gos/components/flexberry-objectlistview.overrides
> +          content: @deleteHelperButtonInRowIcon;
Думаю не получится, придется переписывать верстку. Переменные используются из десктопной версии.

2020-04-23 11:49 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-objectlistview.overrides
> +          content: @deleteHelperButtonInRowIcon;
А если поменять на что-то вроде этого ?
```
.object-list-view .ui.button.object-list-view-row-edit-button .icon:before {
  content: "";
}
```
Так вроде даже одним селектором получается задать.

2020-07-09 13:35 UTC, pepelyaeva approved these changes

2020-07-09 13:42 UTC, merged