Изменены стили для формы редактирования
Flexberry/ember-flexberry-themes pull request #60
Opened 2020-04-15 04:34 UTC by rkapkannikov

Изменены стили для формы редактирования мобильной версии.

2020-04-15 08:04 UTC, pepelyaeva requested changes

2020-04-15 08:04 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-form.overrides
> +    padding-left: 0;
1. Необходимо, чтобы у flexberry-vertical-form остались слева и справа паддинги в 1rem(16px), тк формы могут быть разные, в них может и не быть вложенных .column. При этом формы размеченные по сетке также должны отображаться с отступами в 1rem.
2. Заголовок формы редактирования должен быть 16px, как на списковой форме, сейчас 24px.

2020-04-15 13:19 UTC, KollegOFF commented on src/themes/gos/components/flexberry-form.overrides
> +  form.ui.form.flexberry-vertical-form {
Обязательно ли использовать тег `form` в селекторе?

2020-04-15 13:36 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +    padding-left: 0;
Поправил.

2020-04-15 13:36 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +  form.ui.form.flexberry-vertical-form {
Не обязательно.

2020-04-24 11:40 UTC, pepelyaeva requested changes

2020-04-24 11:40 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-form.overrides
> +    font-size: @formHeaderMobileFontSize;
Нужно использовать [@h1Mobile](https://github.com/Flexberry/ember-flexberry-themes/blob/develop/src/themes/gos/globals/site.variables#L237) - на списке задается этой переменной, таким образом при ее изменении сохраняется однообразие на формах.

2020-04-24 11:40 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
A если будет .ui.two.column.grid.stackable?
На разрешении > 767 отступ пропал.
В семантике задается дополнительный отступ через медиа-запрос, думаю будет правильнее через такой же запрос его и убирать, при этом данный стиль должен быть применен только для грида, который является прямым наследником .flexberry-vertical-form.

2020-04-27 07:47 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +    font-size: @formHeaderMobileFontSize;
Исправил

2020-04-27 07:47 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
Исправил

2020-04-27 08:55 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
Последний пункт? медиа-запрос нужно вынести из .mobile и расположить отдельно от остальных стилей ниже.

2020-04-27 09:28 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
Вынес отдельно

2020-04-27 10:24 UTC, pepelyaeva commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
Это, конечно, хорошо, только ты при этом часть селектора потерял. 

> Данный стиль должен быть применен только для грида, который является прямым наследником .flexberry-vertical-form.

 .flexberry-vertical-form > .ui.column.grid.stackable > .column

2020-04-27 11:16 UTC, rkapkannikov commented on src/themes/gos/components/flexberry-form.overrides
> +    .ui.one.column.grid.stackable > .column {
Добавил

2020-04-29 06:27 UTC, pepelyaeva approved these changes

2020-04-29 06:28 UTC, merged