Стили для логин формы мобильная
Flexberry/ember-flexberry-themes pull request #63
Opened 2020-04-16 08:48 UTC by rkapkannikov

Добавлены стили для логин формы мобильной версии.

2020-04-23 12:44 UTC, pepelyaeva commented on src/themes/gos/pages/login-form.overrides
> +    }
Селекторы можно задавать через запятую.

2020-04-23 12:46 UTC, pepelyaeva commented on src/themes/gos/pages/login-form.overrides
> +    padding: @mobileLoginFormPadding;
Лучше перенести наверх под объявление селектора.

2020-04-23 12:48 UTC, pepelyaeva commented on src/themes/gos/pages/login-form.overrides
> +      font-size: @mobileLoginFormHeaderFontSize;
Задублируется с заданием размера щрифта для формы редактирования.

2020-04-23 13:45 UTC, pepelyaeva requested changes

2020-04-23 13:45 UTC, pepelyaeva commented on src/themes/gos/pages/login-form.overrides
> +    }
Можно в разметке сделать кнопку large

2020-04-24 05:42 UTC, rkapkannikov commented on src/themes/gos/pages/login-form.overrides
> +    }
Убрал теги, объединил селекторы

2020-04-24 05:42 UTC, rkapkannikov commented on src/themes/gos/pages/login-form.overrides
> +    padding: @mobileLoginFormPadding;
Перенёс

2020-04-24 05:43 UTC, rkapkannikov commented on src/themes/gos/pages/login-form.overrides
> +      font-size: @mobileLoginFormHeaderFontSize;
Удалил

2020-04-24 05:43 UTC, rkapkannikov commented on src/themes/gos/pages/login-form.overrides
> +    }
Изменил класс в разметке, удалил стили

2020-04-24 11:43 UTC, pepelyaeva approved these changes

2020-04-29 06:35 UTC, merged