Added styles for uimessage control
Flexberry/ember-flexberry-themes pull request #86
Opened 2020-07-22 10:43 UTC by dpavloff

Added styles for flexberry-uimessage components: new icon, removed border, slightly changed font props

2020-07-23 07:20 UTC, dpavloff commented
23.07.2020
Also removed arrow spinners from flexberry-field [type="number"] (firefox)

2020-08-07 08:03 UTC, KollegOFF commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Давайте без этого?

2020-08-09 13:59 UTC, dpavloff commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Всё таки не стоит убирать стрелочки на number input'ах?

2020-08-10 04:58 UTC, KollegOFF commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Я думаю что не стоит, при желании, это всегда можно сделать в приложении.

2020-08-10 05:19 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-field.overrides
> +}
https://github.com/Flexberry/ember-flexberry-themes/blob/develop/src/definitions/components/flexberry-objectlistview.less#L100 вот тут тоже тогда убрать? или убрать стрелки только для олва? они будут мешать в поле для перехода на страницу.

2020-08-10 06:46 UTC, KollegOFF commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Лучше убрать только для олва в теме `ghost`, в `blue-sky` кнопка отдельно, не будут мешать.

2020-08-10 07:08 UTC, dpavloff commented on src/themes/ghost/components/flexberry-field.overrides
> +}
В таком случае, я сделаю более конкретный селектор, чтобы попадал только на пейджинг олва

2020-08-10 07:11 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Удали тогда, пожалуйста, еще [здесь](https://github.com/Flexberry/ember-flexberry-themes/blob/develop/src/definitions/components/flexberry-objectlistview.less#L100) и добавь -webkit-appearance

2020-08-10 09:28 UTC, dpavloff commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Исправил.

2020-08-31 06:14 UTC, KollegOFF commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Что-то я не понял, тут для разных браузеров разные селекторы?
И у нас вроде `autoprefixer` где-то был...

2020-08-31 16:27 UTC, pepelyaeva requested changes

2020-08-31 16:27 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-uimessage.overrides
> +}
Нужно поиспользовать семантиковые переменные @errorBoxShadow, @warningBoxShadow и тд, и у брать эти стили.

2020-08-31 16:27 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-uimessage.overrides
> +}
Здесь тоже можно обойтись переменными @headerFont, @headerFontWeight

2020-08-31 16:27 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Да, для них по-разному нужно https://stackoverflow.com/questions/23372903/hide-spinner-in-input-number-firefox-29. Можно сделать как-то так

```
.ui.input.nav-bar-search-page input[type='number'] {
  -moz-appearance: textfield;/*For FireFox*/

  &::-webkit-inner-spin-button { /*For Webkits like Chrome and Safari*/
    -webkit-appearance: none;
    margin: 0;
  }
}
```

2020-08-31 16:27 UTC, pepelyaeva commented on src/definitions/components/flexberry-objectlistview.less
>  }
Вот это давай тоже перенесем к -webkit-appearance: none;

2020-08-31 17:31 UTC, dpavloff commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Йеп. В FF это почему-то правило, а в хроме и сафари - псевдокласс. Меня больше смущает то, что селектор от первого не подходит ко второму... Но я думаю это можно исправить.

2020-08-31 17:47 UTC, dpavloff commented on src/themes/ghost/components/flexberry-uimessage.overrides
> +}
Заменил значение переменной с "0 0 0 0 transparent !important" на @errorBoxShadow без !important. Вместо этого добавил 19 селекторов на каждый возможный вариант .ui.message - считаю, что это хороший обмен.

2020-08-31 17:50 UTC, pepelyaeva commented on src/themes/ghost/components/flexberry-uimessage.overrides
> +}
Зачем селекторы? Можно просто переменные переопределить же

2020-08-31 17:52 UTC, dpavloff commented on src/themes/ghost/components/flexberry-uimessage.overrides
> +}
Моей целью было избавиться от !important - такое решение, вроде как, работает. Или я не до конца понял?

2020-09-01 09:57 UTC, dpavloff commented on src/definitions/components/flexberry-objectlistview.less
>  }
Перенёс.

2020-09-14 12:30 UTC, pepelyaeva approved these changes

2020-09-14 12:33 UTC, KollegOFF commented on src/themes/ghost/components/flexberry-field.overrides
> +}
Думаю это больше относится к стилям `flexberry-objectlistview`.

2020-09-14 12:33 UTC, merged